What was done:

1 dataset from the "Transformer-Networks-for-Energy-Time-Series-Forecasting" project was saved as *.csv file, and stored in dataset/afeka/ folder.
    *.csv file contains electricy load data in MH/h in Germany between the years 2015 and 2020
2 new script was added: scripts/afeka/Autoformer.sh
3 Autoformer model has been trained on the new dataset 

In [3]:
import numpy as np

In [ ]:
path = 'results/AFEKA_96_96_Autoformer_custom_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0'

In [6]:
np.load(path + '/metrics.npy')
    

array([0.11002506, 0.07553413, 0.27483472,        inf,        inf],
      dtype=float32)

In [9]:
true_values = np.load(path + '/true.npy')
true_values

array([[[ 1.2247275e+00,  7.0715690e-01,  3.8975105e-01, ...,
          6.7808592e-01,  6.7701721e-01, -1.3907939e+00],
        [ 1.2247275e+00, -7.0707673e-01,  7.5059605e-01, ...,
          6.7808592e-01,  6.7701721e-01, -1.4104648e+00],
        [ 9.2544195e-11, -1.4141935e+00,  1.0557728e+00, ...,
          6.7808592e-01,  6.7701721e-01, -1.1990429e+00],
        ...,
        [-1.2247275e+00, -7.0707673e-01, -3.8975105e-01, ...,
         -1.4747393e+00,  6.7701721e-01, -1.4749699e+00],
        [-1.2247275e+00,  7.0715690e-01, -3.2471630e-11, ...,
         -1.4747393e+00,  6.7701721e-01, -1.6746342e+00],
        [ 9.2544888e-11,  1.4142737e+00, -3.2471276e-11, ...,
         -1.4747393e+00,  6.7701721e-01, -1.6973572e+00]],

       [[ 1.2247275e+00, -7.0707673e-01,  7.5059605e-01, ...,
          6.7808592e-01,  6.7701721e-01, -1.4104648e+00],
        [ 9.2544195e-11, -1.4141935e+00,  1.0557728e+00, ...,
          6.7808592e-01,  6.7701721e-01, -1.1990429e+00],
        [-1.2247275e+00, 

In [10]:
pred_values = np.load(path + '/pred.npy')
pred_values

array([[[ 1.1275238 ,  0.8565434 ,  0.28346017, ...,  0.7766261 ,
          0.7884289 , -1.0806301 ],
        [ 1.2712892 , -0.7164774 ,  0.66819614, ...,  0.83700216,
          0.6434289 , -1.1664369 ],
        [ 0.03837842, -1.5277796 ,  1.0647981 , ...,  0.88128036,
          0.65181726, -0.98570454],
        ...,
        [-1.3005141 , -0.72508377, -0.3859756 , ..., -1.4717448 ,
          0.36890557, -1.4628341 ],
        [-1.4535079 ,  0.621837  ,  0.03361571, ..., -1.3457304 ,
          0.34218943, -1.7341328 ],
        [ 0.20574817,  1.4915448 ,  0.24226117, ..., -1.6322678 ,
          0.37880895, -1.4334468 ]],

       [[ 1.2714221 , -0.5463457 ,  0.65749145, ...,  0.78008664,
          0.811366  , -1.0956924 ],
        [ 0.01360071, -1.4538283 ,  0.98407376, ...,  0.84994435,
          0.73473334, -1.0048648 ],
        [-1.3485588 , -0.79420424,  1.3098686 , ...,  0.84649307,
          0.7509403 , -0.5676398 ],
        ...,
        [-1.3714068 ,  0.6440065 , -0.0839335 , ..., -

In [16]:
import torch
import torch.nn as nn

In [107]:
from layers.Embed import TimeFeatureEmbedding, DataEmbedding_wo_pos

import numpy as np

In [ ]:
d_model=512
c_in = 12
embed_type = 'timeF'

embeding = DataEmbedding_wo_pos(c_in=c_in, d_model=d_model, embed_type=embed_type)
 

t = torch.tensor([ 0.00723475, -1.4853604 , -0.8076481 ,  0.38199094, 0.7281399 , -0.3077886 ])
dfe.forward(t)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x6 and 4x512)